# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd96d84fd9cdb2cdd3d1f28f587c583c9605c144c782d89e537fea85943144a8b45eeebb59de1d546ccae3b6e688dca0d32670e1d78db4695d219498043f41be

test:
  secret_key_base: 735760daa30bf96b941279ccf9f08208476964d981ba283b301c7d182221d4ba93ece2c9e2f1fedfeacdcf6185e4c223f6639d844d4b2a154faebf35b2827632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
